//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AjaxDropdown.Model.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public long Id { get; set; }
        public string CityName { get; set; }
        public Nullable<long> StateId { get; set; }
        public Nullable<long> CountryId { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual State State { get; set; }
    }
}
